---
- hosts: flowers
  remote_user: pi
  connection: paramiko # because we need to specify a password on the first run
  vars:
    ansible_ssh_pass: raspberry # hopefully just for the first run
    hostname: rpi-flowers
    domain: home.silfreed.net
  roles:
    - rpi-common
    - telegraf

#  tasks:
#    - name: vpn packages
#      tags: vpn
#      apt:
#        state: latest
#        pkg:
#          - git
#          - rtl-sdr
#          - golang
