---
- hosts: mc0.ewr.pyxos.net
  remote_user: dwarner
  vars:
    docker:
      - name: minecraft-survival
        docker_hub_image: itzg/minecraft-server
        description: "Minecraft Survival Container"
        docker_env:
          TZ: America/New_York
          MEMORY: 700M
        docker_ports:
          25565: 25565
        docker_vols:
          "/mnt/minecraft/survival": "/data"

  roles:
    - docker

# tasks:
# FIXME: set hostname
# FIXME: disable root ssh
# FIXME: add dwarner user w/ default password and ssh key
# FIXME: add dwarner to wheel
