---
- hosts: thor
  remote_user: silfreed
  vars:
    mkthordocker:
      - name: grafana
        docker_hub_image: grafana/grafana:latest
        description: "Grafana Container"
        lvm:
          - name: grafana_data
            size: 50G
            vg: 12tb_2020
            user: grafana
        docker_env:
        #   GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
          GF_UID: 455
          GF_GID: 452
        docker_ports:
          3000: 3000
        docker_vols:
          "/etc/passwd": "/etc/passwd"
          "/etc/group": "/etc/group"
          "/mnt/grafana_data": "/var/lib/grafana"
        docker_options: |
          --user=455:452 \

      - name: influxdb
        docker_hub_image: influxdb
        description: "InfluxDB Container"
        lvm:
          - name: influxdb
            size: 50G
            vg: 12tb_2020
            user: influxdb
        docker_env:
          PUID: 454
          GUID: 451
          INFLUXDB_DB: db0
          INFLUXDB_ADMIN_USER: admin
          INFLUXDB_ADMIN_PASSWORD: supersecretpassword # FIXME: lookup onepassword
          INFLUXDB_USER: telegraf
          INFLUXDB_USER_PASSWORD: secretpassword # FIXME: lookup onepassword
        docker_ports:
          8086: 8086
        docker_vols:
          "/etc/passwd": "/etc/passwd"
          "/etc/group": "/etc/group"
          "/mnt/influxdb": "/var/lib/influxdb"
        docker_options: |
          --user=454:451 \

      - name: minecraft-survival
        docker_hub_image: itzg/minecraft-server
        description: "Minecraft Survival Container"
        lvm:
          - name: minecraft
            size: 50G
            vg: 500gb_2020_ssd
            mount_options: discard
        docker_env:
          TZ: America/New_York
          # VERSION: SNAPSHOT
          MEMORY: 2G
        docker_ports:
          25565: 25565
        docker_vols:
          "/etc/passwd": "/etc/passwd"
          "/etc/group": "/etc/group"
          "/mnt/minecraft/survival": "/data"
        docker_options: |
          --network=lan5 \
          --ip=192.168.0.194 \

      - name: plexmediaserver
        docker_hub_image: plexinc/pms-docker
        description: "Plex Media Server Container"
        lvm:
          - name: plexmediaserver
            size: 100G
            vg: 12tb_2020
          - name: tv_shows
            size: 1.5T
            vg: 12tb_2020
            mode: "02775"
          - name: movies
            size: 400G
            vg: 12tb_2020
            mode: "02775"
          - name: personal_movies
            size: 400G
            vg: 12tb_2020
            mode: "02775"
          - name: music
            size: 100G
            vg: 12tb_2020
            mode: "02775"
          - name: photos
            size: 400G
            vg: 12tb_2020
            mode: "02775"
        docker_env:
          TZ: "America/New_York"
          PLEX_CLAIM: "claim-bRrsrbVS6hxu6eriWK1b"
          PLEX_UID: 475 # FIXME: lookup UID
          PLEX_GID: 475 # FIXME: lookup GID
        docker_vols:
          "/mnt/plexmediaserver": "/config"
          "/mnt/tv_shows": "/tv-seasons"
          "/mnt/movies": "/movies"
          "/mnt/personal_movies": "/home-movies"
          "/mnt/music": "/music"
          "/mnt/photos/public": "/photos"
        docker_options: |
          --network=lan5 \
          --ip=192.168.0.193 \
          -h HKRoad \

      - name: unifi
        docker_hub_image: jacobalberty/unifi:latest
        description: "Unifi Controller Container"
        lvm:
          - name: unifi
            size: 50G
            vg: 12tb_2020
            mode: "0775"
            user: "unifi"
        docker_env:
          TZ: 'America/New_York'
          RUNAS_UID0: false
          UNIFI_UID: 1001 # FIXME: Lookup UID
          UNIFI_GID: 1001 # FIXME: Lookup GID
        docker_ports:
          8080: 8080
          8443: 8443
          3478: 3478/udp
          10001: 10001/udp
        docker_vols:
          "/mnt/unifi": "/unifi"

      - name: uvc
        docker_hub_image: pducharme/unifi-video-controller:latest
        description: "Unifi Video Controller Container"
        lvm:
          - name: uvc
            size: 750G
            vg: 12tb_2020
            mode: "0775"
            user: "unifi-video"
        docker_env:
          TZ: 'America/New_York'
          PUID: 1002 # FIXME: Lookup UID
          PGID: 1002 # FIXME: Lookup GID
        docker_ports:
          7442: 7442
          7443: 7443
          7444: 7444
          7445: 7445
          7446: 7446
          7447: 7447
          7080: 7080
          6666: 6666
          1935: 1935
        docker_vols:
          "/mnt/uvc": "/var/lib/unifi-video"
          "/mnt/uvc/videos": "/usr/lib/unifi-video/data/videos"
        docker_options: |
          --net=lan5 \
          --ip=192.168.0.192 \
          --cap-add SYS_ADMIN \
          --cap-add DAC_READ_SEARCH \

      - name: unifi-poller
        docker_hub_image: golift/unifi-poller:latest
        description: "Unifi Poller Container"
        docker_env:
          UP_UNIFI_DEFAULT_URL: "https://192.168.0.15:8443"
          UP_UNIFI_DEFAULT_USER: "unifipoller"
          UP_UNIFI_DEFAULT_PASS: "unifipoller" #FIXME: set password via onepassword
          UP_INFLUXDB_URL: "http://192.168.0.15:8086"
          UP_INFLUXDB_USER: "telegraf"
          UP_INFLUXDB_PASS: "secretpassword" #FIXME: set password via onepassword

# FIXME: this needs updated to work with my CM700
#      - name: netgear-scrapers
#        docker_hub_image: iandees/netgear-scrapers
#        description: "NetGear Cable Modem Scraper Container"
#        docker_env:
#          INFLUX_URL: "http://192.168.0.15:8086"
#          INFLUX_USER: "telegraf"
#          INFLUX_PASS: "secretpassword" #FIXME: set password via onepassword
#          INFLUX_DB: "cablemodem"
#          MODEM_PASSWORD: "password" #FIXME: set password via onepassword


  roles:
    - mkthordocker
    - telegraf

