---
- hosts: thor
  remote_user: silfreed

  roles:
    - telegraf

  tasks:
  - name: "ark survival server docker"
    ansible.builtin.include_role:
      name: mkthordocker
      vars_from: arkserver

  - name: "grafana docker"
    ansible.builtin.include_role:
      name: mkthordocker
      vars_from: grafana

  - name: "influxdb docker"
    ansible.builtin.include_role:
      name: mkthordocker
      vars_from: influxdb

  - name: "loki docker"
    ansible.builtin.include_role:
      name: mkthordocker
      vars_from: loki

  - name: "minecraft survival docker"
    ansible.builtin.include_role:
      name: mkthordocker
      vars_from: minecraft-survival

  - name: "newrelic cpm docker"
    ansible.builtin.include_role:
      name: mkthordocker
      vars_from: newrelic-cpm

  - name: "plex media server docker"
    ansible.builtin.include_role:
      name: mkthordocker
      vars_from: plexmediaserver

  - name: "unifi-poller docker"
    ansible.builtin.include_role:
      name: mkthordocker
      vars_from: unifi-poller

  - name: "Promtail host journald config"
    become: true
    template:
      src: promtail-journald_config.yml.j2
      dest: "/etc/promtail/config.yml"
      mode: "0644"
      owner: root
      group: root

  - name: "Promtail log shipping"
    ansible.builtin.include_role:
      name: mkthordocker
      vars_from: promtail-journald
