---
- hosts: thor
  remote_user: silfreed

  # roles:
  #   - telegraf

  tasks:
  - name: "Include each docker config"
    ansible.builtin.include_role:
      name: mkthordocker
      vars_from: thor/mkthordocker
