---
# - name: debug all the things
#   debug:
#     msg: "{{ item }}"
#   loop:
#     - "Name: {{ name }}"
#     - "DHI: {{ docker_hub_image }}"
#     - "Descr: {{ description }}"
#     - "LVM: {{ lvm|default(omit) }}"
#     - "DEnv: {{ docker_env|default(omit) }}"
#     - "DVol: {{ docker_vols|default(omit) }}"
#     - "DOpt: {{ docker_options|default(omit) }}"

# https://opendev.org/openstack/ansible-role-systemd_mount/src/branch/master/tasks/systemd_mounts.yml
# - name: Escape mount service file name
#   command: systemd-escape -p --suffix="mount" "/mnt/{{ item.name }}"
#   changed_when: false
#   register: mount_service_name
#   # set_fact:
#   #   lvm: "{{ lvm:combine(item) }}"
#   # FIXME: ^ How do I register a new key/value into a dictionary defined from the yaml
#   # that will persist across the rest of the role
#   loop: "{{ lvm }}"
#   loop_control:
#     label: "{{ item.name }}"
#   when: lvm is defined and 'user' in item

# - name: Debug LVM update for systemd escaping
#   debug:
#     var: lvm
  
- name: create user for LVM mount
  become: true
  user:
    name: "{{ item.user }}"
    system: yes
  loop: "{{ lvm }}"
  loop_control:
    label: "{{ item.name }}"
  when: lvm is defined and 'user' in item

# FIXME: how do we ensure the user, group, and mode _AFTER_ the volume is mounted?
- name: create LVM mount
  become: true
  file:
    path: "/mnt/{{ item.name }}"
    state: directory
    mode: "{{ item.mode|default('0750') }}"
    owner: "{{ item.user|default(omit) }}"
  loop: "{{ lvm }}"
  loop_control:
    label: "{{ item.name }}"
  when: lvm is defined

- name: collect lvs info
  tags: lvs
  become: true
  check_mode: no
  command: lvs --reportformat=json
  ignore_errors: true
  register: result
  when: lvm is defined

# - name: debug lvs result
#   debug:
#     var: result

- name: set lvs facts
  tags: lvs
  set_fact:
    lvs: "{{ result.stdout | from_json }}"
  when: lvm is defined and result is defined

# - name: debug lvs fact
#   tags: lvs
#   debug:
#     var: lvs
# - name: debug lvs lv_name list
#   tags: lvs
#   debug:
#     var: lvs.report[0].lv|map(attribute='lv_name')|list

- name: Make lvm volume
  tags: mklvm
  become: true
  ansible.builtin.command: lvcreate -L {{ item.size }} {{ item.vg }} -n {{ item.name }} --wipesignatures y --yes
  # debug:
  #   msg: "lvcreate -L {{ item.size }} {{ item.vg }} -n {{ item.name }}"
  loop: "{{ lvm }}"
  loop_control:
    label: "{{ item.name }}"
  when: lvm is defined and item.name not in lvs.report[0].lv|map(attribute='lv_name')|list

- name: format lvm volume
  tags: mklvm
  become: true
  command: mke2fs /dev/{{ item.vg }}/{{ item.name|replace('-','--') }}
  # debug:
  #   msg: "mke2fs /dev/{{ item.vg }}/{{ item.name }}"
  loop: "{{ lvm }}"
  loop_control:
    label: "{{ item.name }}"
  when: lvm is defined and item.name not in lvs.report[0].lv|map(attribute='lv_name')|list

# TODO: detect if LVM volume size is different from configured

- name: Create and mount lvm volume
  become: true
  ansible.posix.mount:
    src: /dev/mapper/{{ item.vg }}-{{ item.name | replace('-', '--') }}
    path: /mnt/{{ item.name }}
    opts: defaults{{ "," + item.mount_options if item.mount_options is defined}}
    state: mounted
    fstype: ext4
    passno: 2
  loop: "{{ lvm }}"
  loop_control:
    label: "{{ item.name }}"
  # TODO: notify a handler to reload the docker instance
  when: lvm is defined

- name: Create docker systemd unit file
  become: true
  ansible.builtin.template:
    src: docker@.service.j2
    dest: "/etc/systemd/system/docker@{{ name }}.service"
    mode: "0644"
    owner: root
    group: root

# FIXME: only force reload when unit files change
- name: force systemd daemon reload when unit files change
  systemd:
    daemon_reload: yes

- name: manage docker systemd unit
  become: true
  systemd:
    state: "{{ state | default('started') }}"
    enabled: "{{ enabled | default('yes') }}"
    name: "docker@{{ name }}.service"
  notify: "reload docker instance"
