---
- name: hkrd base packages
  tags: hkrd
  become: true
  ansible.builtin.package:
    state: latest
    pkg:
      - "{{ ( ansible_facts['distribution'] == 'redhat' ) | ternary ('vim-enhanced', 'vim') }}"
      - htop
      - dstat
