#      - name: awair-to-influxdb
#        docker_hub_image: astundzia/awair-to-influxdb
#        description: "ships awair stats to influxdb"
#          INFLUX_URL: "http://192.168.0.15:8086"
#          INFLUX_USER: "awair"
#          INFLUX_PASS: "{{ lookup('community.general.onepassword', 'HKRoad Ansible Passwords', section='thor', field='influxdb awair pass') }}"
#          INFLUX_DB: "cablemodem"