---
- name: systemctl daemon reload
  become: true
  systemd:
    daemon_reload: yes

- name: reload docker instance
  become: true
  systemd:
    state: restarted
    name: "docker@{{ name }}.service"
#  when: item.changed
