---
- name: add influx yum repo
  become: true
  yum_repository:
    name: influxdb
    description: InfluxDB Repository
    baseurl: https://repos.influxdata.com/stable/$basearch/main/
    gpgkey: https://repos.influxdata.com/influxdata-archive.key
    gpgcheck: yes

- name: install telegraf via dnf
  become: true
  dnf:
    state: latest
    name:
      - telegraf

